### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by ColinAnthony**
finding version numbers matches wrong line in version.h file (probably after seqan update)
added "define" to match string to force match at correct location

version.h file:
```
// ==========================================================================
//                 SeqAn - The Library for Sequence Analysis
// ==========================================================================
// Copyright (c) 2006-2013, Knut Reinert, FU Berlin
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
//     * Redistributions of source code must retain the above copyright
//       notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above copyright
//       notice, this list of conditions and the following disclaimer in the
//       documentation and/or other materials provided with the distribution.
//     * Neither the name of Knut Reinert or the FU Berlin nor the names of
//       its contributors may be used to endorse or promote products derived
//       from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL KNUT REINERT OR THE FU BERLIN BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
// OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
// DAMAGE.
//
// ==========================================================================
// Author: Manuel Holtgrewe <manuel.holtgrewe@fu-berlin.de>
// ==========================================================================
// Define SeqAn version.
// ==========================================================================

#ifndef SEQAN_VERSION_H_
#define SEQAN_VERSION_H_

/**
.Macro.SEQAN_VERSION_MAJOR
..cat:Versioning
..summary:Major SeqAn revision number.
..signature:SEQAN_VERSION_MAJOR
..example:For SeqAn version "1.3", this value is $1$, for "2.5.4", it is $2$.
..include:seqan/version.h

.Macro.SEQAN_VERSION_MINOR
..cat:Versioning
..summary:Minor SeqAn revision number.
..signature:SEQAN_VERSION_MINOR
..example:For SeqAn version "1.3", this value is $3$, for "1.5.4", it is $5$.
..include:seqan/version.h

.Macro.SEQAN_VERSION_PATCH
..cat:Versioning
..summary:SeqAn patch revision number.
..signature:SEQAN_VERSION_PATCH
..example:For SeqAn version "1.3", this value is $0$, for "1.3.4", it is $4$.
..include:seqan/version.h

.Macro.SEQAN_VERSION_PRE_RELEASE
..cat:Versioning
..summary:Flag ($0$/$1$) to indicate whether this is a pre-release (i.e. SVN version).
..signature:SEQAN_VERSION_PRE_RELEASE
..include:seqan/version.h
*/ 

#define SEQAN_VERSION_MAJOR 1

#define SEQAN_VERSION_MINOR 4

#define SEQAN_VERSION_PATCH 1

#define SEQAN_VERSION_PRE_RELEASE 0

#endif  // SEQAN_VERSION_H_
```

### CODE REVIEW

**Comment by iosonofabio** [comment]
Thanks for the PR! It currently fails on Travis because it cannot find `version.h`, is that something you can have a look at?

Also, please do not mix `os.path.join` sparsely into the code. seqanpy is not working on Windows anyway and mixing `/` in most places with a few `os.path.join` sprinkled here and there makes the code quite unreadable...

Thanks!
Fabio

**Comment by ColinAnthony** [comment]
Hi,
I think this could that have been due to the `os.path.join`: 
`seqan_path = os.path.join(seqan_path, "seqan")`
then
 `with open(seqan_path+'/seqan/version.h', 'rt') as f:`
is looking for the obviously wrong 
`/usr/include/seqan/seqan/version.h`
I have changed it back to the original path in `9c7e65e`

**Comment by ColinAnthony** [comment]
Great!
Is there a timeline on updating the pypi package?

**Comment by iosonofabio** [comment]
Whenever I have time, why so urgent?

**Pull request merged**
